# Generated by Django 2.2.1 on 2019-06-24 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_indextitle'),
    ]

    operations = [
        migrations.AddField(
            model_name='indextitle',
            name='image',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
